refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: debug
  appenders:
    - stdout
loggers:
  tokio_core:
    level: info
    appenders:
      - stdout
    additive: false
  tokio_reactor:
    level: info
    appenders:
      - stdout
    additive: false